#!/bin/sh
# Copyright 2012 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# git gofmt pre-commit hook
#
# To use, store as .git/hooks/pre-commit inside your repository and make sure
# it has execute permissions.
#

unformatted=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$' | tr '\n' '\0' | xargs -0 gofmt -l)
[ -z "$unformatted" ] && exit 0
# Some files are not gofmt'd. Print message and fail.

echo >&2 "Go files must be formatted with gofmt. Please run:"
echo "$unformatted" | while read -r fn
do
	echo >&2 "  gofmt -w $PWD/$fn"
done

exit 1
